unit PPLADLLWrapper;

interface

  uses Windows;

  function  A_Bar2d_Maxi(x:integer; y:integer; primary:integer; secondary:integer; country:integer;
            service:integer; mode:char; numeric:integer; data:AnsiString):integer;stdcall;
            external 'WINPPLA.DLL';
  function  A_Bar2d_Maxi_Ori(x:integer; y:integer; ori:integer; primary:integer; secondary:integer;
            country:integer; service:integer; mode:char; numeric:integer; data:AnsiString):integer;
            stdcall;external 'WINPPLA.DLL';
  function  A_Bar2d_PDF417(x:integer; y:integer; narrow:integer; width:integer; normal:char;
            security:integer; aspect:integer; row:integer; column:integer; mode:char;
            numeric:integer; data:AnsiString):integer;stdcall;external 'WINPPLA.DLL';
  function  A_Bar2d_PDF417_Ori(x:integer; y:integer; ori:integer; narrow:integer; width:integer;
            normal:char; security:integer; aspect:integer; row:integer; column:integer; mode:char;
            numeric:integer; data:AnsiString):integer;stdcall;external 'WINPPLA.DLL';
  function  A_Bar2d_DataMatrix(x:integer; y:integer; rotation:integer; hor_mul:integer;
            ver_mul:integer; ECC:integer; data_format:integer; num_rows:integer; num_col:integer;
            mode:char; numeric:integer; data:AnsiString):integer;stdcall;external 'WINPPLA.DLL';
  Procedure A_Clear_Memory();stdcall;external 'WINPPLA.DLL';
  Procedure A_ClosePrn();stdcall;external 'WINPPLA.DLL';
  function  A_CreatePrn(selection:integer; filename:AnsiString):integer;stdcall;
            external 'WINPPLA.DLL';
  function  A_Del_Graphic(mem_mode:integer; graphic:AnsiString):integer;stdcall;external 'WINPPLA.DLL';
  function  A_Draw_Box(mode:char; x:integer; y:integer; width:integer; height:integer; top:integer;
            side:integer):integer;stdcall;external 'WINPPLA.DLL';
  function  A_Draw_Line(mode:char; x:integer; y:integer; width:integer; height:integer):integer;
            stdcall;external 'WINPPLA.DLL';
  Procedure A_Feed_Label();stdcall;external 'WINPPLA.DLL';
  function  A_Get_DLL_Version(nShowMessage:integer):PAnsiChar;stdcall;external 'WINPPLA.DLL';
  function  A_Get_DLL_VersionA(nShowMessage:integer):integer;stdcall;external 'WINPPLA.DLL';
  function  A_Get_Graphic(x:integer; y:integer; mem_mode:integer; format:char; filename:AnsiString):integer;
            stdcall;external 'WINPPLA.DLL';
  function  A_Get_Graphic_ColorBMP(x:integer; y:integer; mem_mode:integer; format:char;
            filename:AnsiString):integer;stdcall;external 'WINPPLA.DLL';
  function  A_Get_Graphic_ColorBMPEx(x:integer; y:integer; nWidth:integer; nHeight:integer;
            rotate:integer; mem_mode:integer; format:char; id_name:AnsiString; filename:AnsiString):integer;
            stdcall;external 'WINPPLA.DLL';
  function  A_Get_Graphic_ColorBMP_HBitmap(x:integer; y:integer; nWidth:integer; nHeight:integer;
            rotate:integer; mem_mode:integer; format:char; id_name:AnsiString; hbm:HBITMAP):integer;
            stdcall;external 'WINPPLA.DLL';
  function  A_Initial_Setting(Type_Renamed:integer; Source:AnsiString):integer;stdcall;
            external 'WINPPLA.DLL';
  function  A_WriteData(IsImmediate:integer; pbuf:AnsiString; length:integer):integer;stdcall;
            external 'WINPPLA.DLL';
  function  A_ReadData(pbuf:PAnsiChar; length:integer; dwTimeoutms:integer):integer;stdcall;
            external 'WINPPLA.DLL';
  function  A_Load_Graphic(x:integer; y:integer; graphic_name:AnsiString):integer;stdcall;
            external 'WINPPLA.DLL';
  function  A_Open_ChineseFont(path:AnsiString):integer;stdcall;external 'WINPPLA.DLL';
  function  A_Print_Form(width:integer; height:integer; copies:integer; amount:integer;
            form_name:AnsiString):integer;stdcall;external 'WINPPLA.DLL';
  function  A_Print_Out(width:integer; height:integer; copies:integer; amount:integer):integer;
            stdcall;external 'WINPPLA.DLL';
  function  A_Prn_Barcode(x:integer; y:integer; ori:integer; type_Renamed:char; narrow:integer;
            width:integer; height:integer; mode:char; numeric:integer; data:AnsiString):integer;
            stdcall;external 'WINPPLA.DLL';
  function  A_Prn_Text(x:integer; y:integer; ori:integer; font:integer; type_Renamed:integer;
            hor_factor:integer; ver_factor:integer; mode:char; numeric:integer; data:AnsiString):integer;
            stdcall;external 'WINPPLA.DLL';
  function  A_Prn_Text_Chinese(x:integer; y:integer; fonttype:integer; id_name:AnsiString; data:AnsiString;
            mem_mode:integer):integer;stdcall;external 'WINPPLA.DLL';
  function  A_Prn_Text_TrueType(x:integer; y:integer; FSize:integer; FType:AnsiString; Fspin:integer;
            FWeight:integer; FItalic:integer; FUnline:integer; FStrikeOut:integer; id_name:AnsiString;
            data:AnsiString; mem_mode:integer):integer;stdcall;external 'WINPPLA.DLL';
  function  A_Prn_Text_TrueType_W(x:integer; y:integer; FHeight:integer; FWidth:integer;
            FType:AnsiString; Fspin:integer; FWeight:integer; FItalic:integer; FUnline:integer;
            FStrikeOut:integer; id_name:AnsiString; data:AnsiString; mem_mode:integer):integer;
            stdcall;external 'WINPPLA.DLL';
  function  A_Set_Backfeed(back:integer):integer;stdcall;external 'WINPPLA.DLL';
  function  A_Set_BMPSave(nSave:integer; pstrBMPFName:AnsiString):integer;stdcall;
            external 'WINPPLA.DLL';
  function  A_Set_Cutting(cutting:integer):integer;stdcall;external 'WINPPLA.DLL';
  function  A_Set_Darkness(heat:UINT):integer;stdcall;external 'WINPPLA.DLL';
  function  A_Set_DebugDialog(nEnable:integer):integer;stdcall;external 'WINPPLA.DLL';
  function  A_Set_Feed(rate:char):integer;stdcall;external 'WINPPLA.DLL';
  function  A_Set_Form(formfile:AnsiString; form_name:AnsiString; mem_mode:integer):integer;stdcall;
            external 'WINPPLA.DLL';
  function  A_Set_Margin(position:integer; margin:integer):integer;stdcall;external 'WINPPLA.DLL';
  function  A_Set_Prncomport(baud:integer; parity:integer; data:integer; stop:integer):integer;
            stdcall;external 'WINPPLA.DLL';
  function  A_Set_Prncomport_PC(nBaudRate:integer; nByteSize:integer; nParity:integer;
            nStopBits:integer; nDsr:integer; nCts:integer; nXonXoff:integer):integer;stdcall;
            external 'WINPPLA.DLL';
  function  A_Set_Sensor_Mode(type_Renamed:char; continuous:integer):integer;stdcall;
            external 'WINPPLA.DLL';
  function  A_Set_Speed(speed:char):integer;stdcall;external 'WINPPLA.DLL';
  function  A_Set_Syssetting(transfer:integer; cut_peel:integer; length:integer; zero:integer;
            pause:integer):integer;stdcall;external 'WINPPLA.DLL';
  function  A_Set_Unit(unit_Renamed:char):integer;stdcall;external 'WINPPLA.DLL';
  function  A_Set_Gap(gap:integer):integer;stdcall;external 'WINPPLA.DLL';
  function  A_Set_Logic(logic:integer):integer;stdcall;external 'WINPPLA.DLL';
  function  A_Set_ProcessDlg(nShow:integer):integer;stdcall;external 'WINPPLA.DLL';
  function  A_Set_LabelVer(centiInch:integer):integer;stdcall;external 'WINPPLA.DLL';
  function  A_GetUSBBufferLen():integer;stdcall;external 'WINPPLA.DLL';
  function  A_EnumUSB(buf:PAnsiChar):integer;stdcall;external 'WINPPLA.DLL';
  function  A_CreateUSBPort(nPort:integer):integer;stdcall;external 'WINPPLA.DLL';
  function  A_CreatePort(nPortType:integer; nPort:integer; filename:AnsiString):integer;stdcall;
            external 'WINPPLA.DLL';
  function  A_Clear_MemoryEx(nMode:integer):integer;stdcall;external 'WINPPLA.DLL';
  Procedure A_Set_Mirror();stdcall;external 'WINPPLA.DLL';
  function  A_Bar2d_RSS(x:integer; y:integer; ori:integer; ratio:integer; height:integer;
            rtype:char; mult:integer; seg:integer; data1:AnsiString; data2:AnsiString):integer;stdcall;
            external 'WINPPLA.DLL';
  function  A_Bar2d_QR_M(x:integer; y:integer; ori:integer; mult:char; value:integer; model:integer;
            error:char; mask:integer; dinput:char; mode:char; numeric:integer; data:AnsiString):integer;
            stdcall;external 'WINPPLA.DLL';
  function  A_Bar2d_QR_A(x:integer; y:integer; ori:integer; mult:char; value:integer; mode:char;
            numeric:integer; data:AnsiString):integer;stdcall;external 'WINPPLA.DLL';
  function  A_GetNetPrinterBufferLen():integer;stdcall;external 'WINPPLA.DLL';
  function  A_EnumNetPrinter(buf:PAnsiChar):integer;stdcall;external 'WINPPLA.DLL';
  function  A_CreateNetPort(nPort:integer):integer;stdcall;external 'WINPPLA.DLL';
  function  A_Prn_Text_TrueType_Uni(x:integer; y:integer; FSize:integer; FType:AnsiString; Fspin:integer;
            FWeight:integer; FItalic:integer; FUnline:integer; FStrikeOut:integer; id_name:AnsiString;
            data:PWideChar; format:integer; mem_mode:integer):integer;stdcall;external 'WINPPLA.DLL';
  function  A_Prn_Text_TrueType_UniB(x:integer; y:integer; FSize:integer; FType:AnsiString; Fspin:integer;
            FWeight:integer; FItalic:integer; FUnline:integer; FStrikeOut:integer; id_name:AnsiString;
            data:PWideChar; format:integer ; mem_mode:integer):integer;stdcall;external 'WINPPLA.DLL';
  function  A_GetUSBDeviceInfo(nPort:integer; pDeviceName:PAnsiChar; pDeviceNameLen:PInteger;
            pDevicePath:PAnsiChar; pDevicePathLen:PInteger):integer;stdcall;external 'WINPPLA.DLL';
  function  A_Set_EncryptionKey(encryptionKey:AnsiString):integer;stdcall;external 'WINPPLA.DLL';
  function  A_Check_EncryptionKey(decodeKey:AnsiString; encryptionKey:AnsiString;
            dwTimeoutms:integer):integer;stdcall;external 'WINPPLA.DLL';

implementation

end.
